Refactoring WIP
wobcom/cosmo pull request #31
Opened 2024-09-17 12:07 UTC by loulecrivain

WIP

2025-02-12 10:59 UTC, loulecrivain commented
all tests passing! I have refactored only the switch serializer for now. there is a lot of additions since the new code is a bit more verbose and I had to add tons of classes to be able to have that "framework".

2025-02-26 19:17 UTC, johannwagner reviewed
Very neat implementation, I like it a lot!

I would like to talk in a call about the code paths around CPE filter list generation and `bgp:cpe` in general to get a better understanding!

Otherwise, it is mostly clean-up and nitpicking, but a call to go through this together and do some knowledge transfer would be a good idea anyways.

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +# every quarter. so, instead of having a billion attribute
I love it!

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +class DeviceType(AbstractNetboxType):
We can simplify the getters here:

```
>>> f = dict()
>>> f.get("foo")
>>> f.get("foo", 3)
3
>>> f.get("serial")
>>> f.get("serial") == None
True


```

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +        if "interfaces" in self:
Can be simplified...

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +        if "serial" in self and self["serial"]:
Can be simplified...

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +class InterfaceType(AbstractNetboxType):
...also able to simplify.

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +            # outer_tag usage, since there's no native type in netbox
Let's throw an error here, if `outer_tag` and `untagged_vlan` is used together.

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +        if "." in self.getName():
`return "." in self.getName()`

2025-02-26 19:17 UTC, johannwagner commented on cosmo/types.py
> +    def spitInterfacePathWith(self, d: dict) -> dict:
What does this do? Can we have an explaining comment how and when to use it?

2025-02-26 19:17 UTC, johannwagner commented on cosmo/switchvisitor.py
> +                        "mtu": 1_500 if not parent_interface.getMTU() else parent_interface.getMTU(),
`parent_interface.getMTU() or 1500`

2025-02-26 19:17 UTC, johannwagner commented on cosmo/switchvisitor.py
> +class SwitchDeviceExporterVisitor(AbstractNoopNetboxTypesVisitor):
This looks very clean!

2025-02-26 19:17 UTC, johannwagner commented on cosmo/routervisitor.py
> +        self.my_l2vpn_exporter = RouterL2VPNExporterVisitor(loopbacks_by_device=loopbacks_by_device, my_asn=my_asn)
I personally don't like `my_` prefixed variables..

2025-02-27 09:37 UTC, loulecrivain commented on cosmo/routervisitor.py
> +        if o.getParent(): # not root, do not process!
this is because devices can contain devices due to l2vpn terminations. by default the visitor doesn't make any difference, so I need to add this guard condition

2025-02-27 09:45 UTC, loulecrivain commented on cosmo/clients/netbox_v4.py
> +                    name
I checked timings before/after changing GraphQL query. It's a little bit slower but not catastrophic. I can't really do without the type hinting, so....

2025-02-27 10:08 UTC, loulecrivain commented on cosmo/types.py
> +    def spitInterfacePathWith(self, d: dict) -> dict:
basically, we need to construct different dictionary paths depending on if an interface is a sub-interface or not. the interface object knows best, so I delegated this functionality to it. this is to avoid having to repeat the same code in every function.

I'll add a comment.

2025-02-27 10:19 UTC, loulecrivain commented on cosmo/types.py
> +class DeviceType(AbstractNetboxType):
will do, thanks!

2025-02-27 10:52 UTC, loulecrivain commented on cosmo/routerl2vpnvisitor.py
> +        if o.getType().lower() == "vpws" and len(terminations) != self._vpws_authorized_terminations_n:
ok, will do. I wasn't sure, because this check was not made in the original code.

2025-02-27 10:58 UTC, loulecrivain commented on cosmo/routervisitor.py
> +                                            o.getIPInterfaceObject().network.hosts()
done

2025-02-27 11:48 UTC, loulecrivain commented on cosmo/types.py
> +            # outer_tag usage, since there's no native type in netbox
done!

2025-02-27 12:20 UTC, loulecrivain commented on cosmo/routervisitor.py
> +            return # guard: do not process (can be connected_endpoint, parent, etc...)
Feel free to close this comment if you do not have further questions :sunglasses:

2025-02-27 14:32 UTC, johannwagner commented on cosmo/routervisitor.py
> +                return self.processInterfaceLagInfo(o)
`processInterfaceLagMemberInfo(o)`

2025-02-27 14:32 UTC, johannwagner commented on cosmo/routervisitor.py
> +        else:
This `else` is obsolete, since every path in the if-clause returns.

2025-02-28 17:43 UTC, loulecrivain commented
@johannwagner all differences on ```ansible_junos``` are resolved, ready for review!

2025-02-28 17:55 UTC, loulecrivain commented
FYI I changed some stuff in the [L2VPN visitors](https://github.com/wobcom/cosmo/blob/refactor/cosmo/routerl2vpnvisitor.py).

Now all L2VPN types and their available encapsulations are modeled with [dedicated types](https://github.com/wobcom/cosmo/blob/refactor/cosmo/l2vpnhelpertypes.py).

The code is a bit more boilerplate, but in the end it's less lines than before (!) and IMO less error-prone, since we no longer have to meddle in with all the different cases for L2VPN types.

The only thing to pay attention to is the order of the encapsulation traits, the one with the most priority should always be 1st.

If you have some ideas to make this part simpler, feel free. Didn't really find a satisfactory solution on my end.

2025-03-03 08:00 UTC, johannwagner requested changes

2025-03-03 08:20 UTC, johannwagner commented on cosmo/__main__.py
>                  router_serializer_cfg = RouterSerializerConfig(cosmo_configuration.get("router_serializer_configuration", {}))
`router_serializer_cfg` is unused now.

2025-03-03 08:23 UTC, johannwagner requested changes

2025-03-03 08:23 UTC, johannwagner commented on cosmo/serializer.py
> +    # TODO: delete me! no longer used
Delete it!

2025-03-03 10:02 UTC, loulecrivain commented on cosmo/common.py
> +class ObjCache:
yes. I'll delete it.

2025-03-03 10:03 UTC, loulecrivain commented on cosmo/l2vpnhelpertypes.py
> +    def getAcceptedTerminationTypes() -> (tuple[type[AbstractNetboxType], type[AbstractNetboxType]]
Ah, good catch. I forgot it was possible to do that :see_no_evil: I'll make an abstract type.

2025-03-03 10:05 UTC, loulecrivain commented on cosmo/__main__.py
>                  router_serializer_cfg = RouterSerializerConfig(cosmo_configuration.get("router_serializer_configuration", {}))
right, will delete it.

2025-03-03 10:08 UTC, loulecrivain commented on cosmo/common.py
> +class ObjCache:
Ah, whoops! Tuns out it is (in the switch serializer)

2025-03-03 10:27 UTC, loulecrivain commented on cosmo/l2vpnhelpertypes.py
> +    def getAcceptedTerminationTypes() -> (tuple[type[AbstractNetboxType], type[AbstractNetboxType]]
can't use an array, since `isinstance` only accepts `class` or `tuple`

2025-03-03 10:47 UTC, loulecrivain commented on cosmo/l2vpnhelpertypes.py
> +# FIXME simplify this!
done so here:
https://github.com/wobcom/cosmo/issues/42

2025-03-03 10:55 UTC, johannwagner approved these changes

2025-03-03 10:56 UTC, merged

2025-03-03 10:57 UTC, loulecrivain commented
:partying_face: